snu910501/sparta_final_week

controllers/comments.controller.js, controllers/posts.controller.js, models/posts.js, models/users.js, package-lock.json, routes/comments.route.js, routes/posts.route.js
fix: Modify posts, comment API, Fix typo in models
=> fix: Modify posts, comment API, Fix typo in models

controllers/comments.controller.js, controllers/posts.controller.js
fix : Modify userId in controller
=> fix : Modify userId in controller

.prettierrc, app.js, controllers/posts.controller.js, middlewares/multer.postImage.js, models/posts.js, modules/errorHandler.js, package-lock.json, package.json, prettier.js, repositories/posts.repository.js, routes/posts.route.js, services/posts.service.js, validations/comment.validation.js, validations/post.validation.js
refactoring post, comment API
@hapi/boom라이브러리와 errorHandler 추가로 try, catch에서의 에러 response 코드 축약
joi 라이브러리를 이용한 validation에서 '    ' 공백문자열에 대한 유효성검사를 위해 trim()옵션 추가
post API 전체적인 구조 변경으로 인한 post API 코드 로직 변경
prettierrc의 중복된 파일 2개 제거
마이페이지의 내가 쓴 게시글 조회를 위한 getMyPost API 추가, uservalidation 추가 
multer를 이용한 업로더에 이미지 파일만 수용하도록 fileFilter적용
대용량 파일 반복전송을 이용한 DOS공격을 막기 위한 multer 파일 리미트 제한
=> refactoring post, comment API

package-lock.json, services/posts.service.js
게시글 수정 시 부족한 if문의 조건 내용 추가
git pull 후 npm i 한 내용으로 package-lock 내용 변경
=> fix/ Modify if statement in updatepost

controllers/comments.controller.js, repositories/comments.repository.js, routes/comments.route.js, services/comments.service.js
=> feat/Add getMyComment API

ReadMe.md, repositories/comments.repository.js, services/posts.service.js
readme 내용 수정
댓글 조회시 commentId 필요 요청 받아서 수정해서 올림
지역게시글이 없을때 빈비열이 전송되던 부분 에러처리
=> fix: Modify readme, getcomment res , post error

repositories/comments.repository.js
=> fix/ Modify typo in getComments res

controllers/comments.controller.js, controllers/posts.controller.js, repositories/comments.repository.js, services/comments.service.js
res.locals의 내용이 바뀜에 따라 post와 comment의 controller에서 userId 를 받아오는 부분을 변경
comment의 service의 에러처리를 위한 if문 조건 변경
댓글 삭제 로직을 그대로 적용하기 위해 대댓글의 응답값에 commentId 추가
=> Taehyung/ fix post, comment API 

controllers/posts.controller.js, repositories/posts.repository.js, services/posts.service.js, validations/post.validation.js
=> fix/ Add postLocation at updatePost

repositories/posts.repository.js
디자인변경으로 인해 내 게시글 조회에서 내용이 추가되어 content추가
게시글 번호 postId는 삭제
=> fix/Modify My Post due to design changes

controllers/comments.controller.js, controllers/posts.controller.js, middlewares/sanitizer.js, package-lock.json, package.json, routes/comments.route.js, routes/posts.route.js, validations/comment.validation.js, validations/post.validation.js
게시글과 댓글의 입력값에 Xss공격에 대한 방어 기재로 sanitizer추가
그에 따른 API수정 
게시글, 댓글 라우터에 기능 설명 주석 추가
=> feat / Add sanitize-Html package

controllers/comments.controller.js, controllers/posts.controller.js, middlewares/sanitizer.js, repositories/posts.repository.js, routes/posts.route.js, services/comments.service.js, services/posts.service.js, validations/post.validation.js
게시글 댓글 순 조회, 최신순 조회 API에 pagenation 추가
이전게시글 API, 다음게시글 API, 검색기능 API 추가
댓글 서비스 부분에서 예외처리 변경
=> Taehyung/ Add pagenation, previous, next,  search post API

repositories/posts.repository.js
commentCount 가 상세조회에서 없어짐에 따라 
attributes를 사용할 필요없이 정보를 다 출력하게 되어 attributes부분 제거
=> refactor/Refactoring Post API

repositories/posts.repository.js, services/posts.service.js, validations/post.validation.js
=> Develope/Modify test service  

controllers/posts.controller.js, repositories/posts.repository.js, routes/posts.route.js, services/posts.service.js, validations/post.validation.js
3개로 나누어진 게시글  댓글 순 조회, 최신 순 조회, 게시글 검색 API를 하나의 API로 통합
=> Taehyung / refactor/ Combine recent, Location, search postAPI

controllers/posts.controller.js, repositories/posts.repository.js, routes/posts.route.js, services/posts.service.js, validations/post.validation.js
=> Develope/ refactor/ Combine recent, Location, search postAPI

controllers/posts.controller.js, repositories/posts.repository.js, routes/posts.route.js, services/posts.service.js
이전 게시글, 다음게시글 API를 삭제하고, 게시글 상세조회에 추가적인 정보를 보내줌
=> refactor/Combine previous, next, detail postAPI

repositories/posts.repository.js
프론트 엔드 요청에 의한 pagenation 다시 수정
=> Taehyung/fix/Modify getLocationPosts pagenation

repositories/posts.repository.js
내가 쓴 게시글 보기 API에서 누락된 postId 추가
=> Taehyung/fix/Add postId at getMyPost API

services/posts.service.js
=> fix/Modify deletePost error 

repositories/posts.repository.js, services/posts.service.js
=> Develope/fix/Modify deletePost error 

repositories/posts.repository.js
무한스크롤을 위한 페이지네이션 작업 우선순위 변경으로 인해 주석 처리
=> fix/Delete pagination by FE request

controllers/posts.controller.js
=> fix/Fix error in getLocationPosts

controllers/posts.controller.js, modules/errorHandler.js, repositories/posts.repository.js, services/posts.service.js, validations/post.validation.js
제목 50글자 인데 50바이트 기준이 되어 100바이트로 변경
에러 메시지 오리지날 메시지 추가
=> Taehyung/Modify postTitle maxLength

repositories/posts.repository.js
=> fix/Modify pagenation limit, offset

services/posts.service.js
=> fix/remove error handling in getPosts

repositories/posts.repository.js, services/posts.service.js
=> Develope/remove error handling in getPosts

middlewares/multer.postImage.js
[이미지 파일 필터 용량 제한 크기 변경](https://github.com/snu910501/sparta_final_week/pull/105)
=> fix/Modify postImage maxfileSize

middlewares/multer.postImage.js, services/posts.service.js
=> Develope/Modify postImage maxfileSize
